Remove quizzes from config
starknet-id/quest_server pull request #247
Opened 2024-08-22 22:52 UTC by LazarusAA

This Pull Request closes issue #240. It includes the following changes:

- Removed quiz section from the config template
- Removed the quizzes fields from the config parser

This PR has been done as part of OnlyDust's ODHack 7.0

2024-08-22 22:54 UTC, LazarusAA commented
Hi @Marchand-Nicolas

I was assigned this issue for ODHack 7.0. Please review and merge or request the required changes if required.

2024-08-23 05:54 UTC, Marchand-Nicolas requested changes
Hello, thanks for your PR! This is almost perfect, but we want to keep the types (see bellow I indicated which parts of the code) because even if we don't read quizzes from the config anymore, we are now loading quizzes from the db and thus still use the types.

2024-08-23 05:54 UTC, Marchand-Nicolas commented on src/config.rs
> -}
This should be kept

2024-08-23 05:54 UTC, Marchand-Nicolas commented on src/config.rs
> -});
This should also be kept

2024-08-23 09:40 UTC, LazarusAA commented
Thanks for the feedback, it makes total sense. I just added the types back, please review and notify me if any changes are required.

2024-08-24 10:47 UTC, Marchand-Nicolas approved these changes
Perfect LGTM!

2024-08-24 10:47 UTC, merged