cleanup-update
starknet-id/quest_server pull request #255
Opened 2024-08-29 10:51 UTC by pheobeayo

2024-08-29 10:52 UTC, pheobeayo commented
update has been done on the clean up

2024-08-29 16:56 UTC, Marchand-Nicolas requested changes
Need to update the code.
Also no need to open a new PR each time you have a change to do. Simply add more commits

2024-08-29 16:56 UTC, Marchand-Nicolas commented on src/endpoints/achievements/verify_seniority.rs
> +            let timestamp_u64 = 1657113606;
Please don't use a static timestamp

2024-08-29 23:22 UTC, pheobeayo commented
made a commit

2024-08-30 10:13 UTC, Marchand-Nicolas requested changes
The "duration" should not be equal to the date_time, instead you should subtract the current time. Here's a piece of code that might help you:
```rs
      let current_time = Utc::now();
      let duration = current_time - date_time;
      let days_passed = duration.num_days();
```

2024-08-30 10:50 UTC, Marchand-Nicolas approved these changes
Well done Lgtm!

2024-08-30 10:50 UTC, merged