Replace admin auth macro by middleware
starknet-id/quest_server pull request #256
Opened 2024-08-30 12:06 UTC by Ugo-X

# Implement Authorization Middleware

Closes #245

2024-08-30 12:32 UTC, Marchand-Nicolas requested changes
A few changes, but after that we can merge I think!

2024-08-30 12:32 UTC, Marchand-Nicolas commented on src/config.rs
> +use std::collections::HashMap;
Can you remove this change from the PR (maybe need to merge ?)

2024-08-30 12:32 UTC, Marchand-Nicolas commented on src/endpoints/achievements/verify_seniority.rs
> -use chrono::{Utc, DateTime};
Also remove these changes

2024-08-30 12:32 UTC, Marchand-Nicolas commented on src/main.rs
> +    //     .layer(axum::middleware::from_fn(auth_middleware));
What is this comment for ?

2024-08-30 12:32 UTC, Marchand-Nicolas commented on src/middleware.rs
> +    let secret_key = b"your_secret_key"; // Replace with the actual secret key (sorry for this)
Don't write the secret in the code (import from config). Instead of this whole block of code you can simply reuse the `check_authorization!` macro imo.

2024-08-30 12:32 UTC, Marchand-Nicolas commented on src/endpoints/admin/user/create_user.rs
> -    };
Keep this code here, as we still want to check that the user is a "super_user". But please delete the `let user = check_authorization!(headers, &state.conf.auth.secret_key.as_ref()) as String;` from all the other files that doesn't have a check for "super_user"

2024-08-30 12:32 UTC, Marchand-Nicolas commented on src/main.rs
> +        .with_state(shared_state.clone());
All the routes are protected, but we don't want this. E.g. `/get_quests` should not require the user to be admin. Only routes starting with `/amin/` should be protected. Also, there is no `/register` route (because only a super-user admin can create another admin account)

2024-08-31 12:02 UTC, Ugo-X commented on src/main.rs
> +    //     .layer(axum::middleware::from_fn(auth_middleware));
removed

2024-08-31 12:03 UTC, Ugo-X commented on src/config.rs
> +use std::collections::HashMap;
removed ser

2024-08-31 12:03 UTC, Ugo-X commented on src/middleware.rs
> +    let secret_key = b"your_secret_key"; // Replace with the actual secret key (sorry for this)
done

2024-08-31 12:04 UTC, Ugo-X commented on src/main.rs
> +        .with_state(shared_state.clone());
done ser

2024-08-31 13:01 UTC, Marchand-Nicolas requested changes
The middleware is still not implemented in all admin pages, and for the one where it is implemented, I get 404 errors (the route is not found), e.g.: /admin/tasks/custom/update. I suggest you to try your code to check everything is working before pushing. Here is a super cool tool to test requests (you can download the app or use it in the browser: https://httpie.io/

2024-08-31 13:01 UTC, Marchand-Nicolas commented on src/endpoints/achievements/verify_seniority.rs
> +            let duration = current_time - dt;
Still seeing these changes. You can either manually do a commit where you simply copy/paste the code from the current file version on the testnet branch (https://github.com/starknet-id/api.starknet.quest) or rebase your branch.
<img width="1075" alt="image" src="https://github.com/user-attachments/assets/945217da-1995-44bf-98a5-80c606819392">

2024-09-01 09:12 UTC, Ugo-X commented on src/endpoints/achievements/verify_seniority.rs
> +            let duration = current_time - dt;
i used the manual commiting method

2024-09-01 09:14 UTC, Ugo-X commented
> The middleware is still not implemented in all admin pages, and for the one where it is implemented, I get 404 errors (the route is not found), e.g.: /admin/tasks/custom/update. I suggest you to try your code to check everything is working before pushing. Here is a super cool tool to test requests (you can download the app or use it in the browser: https://httpie.io/

The route for this is /admin/tasks/custom/update_custom ser

2024-09-02 16:22 UTC, Marchand-Nicolas requested changes
I get this error when trying with /admin/tasks/balance/update_balance (I tested a random route, so I think there is the same issue with all other routes)
```c
Missing request extension: Extension of type `alloc::sync::Arc<quest_server::models::AppState>` was not found. Perhaps you forgot to add it? See `axum::Extension`.
```

2024-09-02 16:22 UTC, Marchand-Nicolas commented on src/endpoints/admin/balance/update_balance.rs
> +    Router::new().route("/update_balance", post(update_balance_handler))
Originally the route was `/admin/tasks/balance/update` but with your PR it becomes `/admin/tasks/balance/update_balance`. You did this kind of update in a lost of routes, can you please put back the old route names so that there is no work to do on the front to adapt the urls ?

2024-09-04 20:22 UTC, Marchand-Nicolas requested changes
The code seems to be working fine for me, so well done!
I added some comments to clean it, because the routing system is currently a bit heavy.

2024-09-04 20:22 UTC, Marchand-Nicolas commented on src/router/admin_routes.rs
> +        .route("tasks/remove_task", post(admin::delete_task::handler))
You forgot the "/" at the start of `tasks/remove_task`.
Are you running the project to test? Because this makes a compilation error on my side. If you need help to setup the config don't hesitate to ask.

2024-09-04 20:22 UTC, Marchand-Nicolas commented on src/middleware/auth.rs
> +    let conf = config::load();
Please do not reload the config. You should use 
```rs
Extension(state): Extension<Arc<AppState>>,
```
in the params of your function, as suggested here: https://gist.github.com/Marchand-Nicolas/e37b14c5d8e5d04492067ea8320fe7e4
so that you can do state.config

2024-09-04 20:22 UTC, Marchand-Nicolas commented on src/endpoints/admin/quest/get_tasks.rs
> -#[route(get, "/admin/quest/get_tasks")]
Keep this as it was before, so that you don't have to do a whole new routing system.
You just adapt it by simply adding the middleware:
```rs
#[route(get, "/admin/quest/get_tasks", auth_middleware)]
```

2024-09-04 20:22 UTC, Marchand-Nicolas commented on src/router/admin_routes.rs
> +        .route("/quest/update", post(admin::quest::update_quest::handler))
All this routing system is a lot of code.
Rather than doing that, you can apply this comment: https://github.com/starknet-id/api.starknet.quest/pull/256#discussion_r1744365749 to all the admin routes

2024-09-05 12:39 UTC, Marchand-Nicolas requested changes
Well done! This is really good job. It works perfectly and the code is super clean, thanks! Just one really quick change (an unused macro to delete)

2024-09-05 12:39 UTC, Marchand-Nicolas commented on src/utils.rs
>  macro_rules! check_authorization {
Can you remove this macro as this is not used anymore please

2024-09-05 12:39 UTC, Marchand-Nicolas commented on Cargo.toml
> +axum_auto_routes = { git = "https://github.com/Th0rgal/axum_auto_routes.git", rev = "4bcae49628a657ed4bdc1749dfd4f1221ffaffe7" }
Very good idea gg!

2024-09-05 12:39 UTC, Marchand-Nicolas commented on src/endpoints/admin/delete_task.rs
> +    Extension(sub): Extension<String>,
This is super cool well done!

2024-09-05 13:05 UTC, Marchand-Nicolas approved these changes
Lgtm! Well done!

2024-09-05 13:06 UTC, merged