add custom_api directory with create and update
starknet-id/quest_server pull request #272
Opened 2024-09-28 03:01 UTC by GideonBature

completed the task by adding the `custom_api` directory and setting up the `POST` and `PUT` method for it. Also, added the `api_url` and `regex` fields to the `QuestTaskDocument` in the `models.rs` file. Also made changes to all the files using the `QuestTaskDocument` to include the `api_url` and the `regex` fields, setting their values as None, since they are not needed in those other context, at least in this scope. I also did this to remove likely errors that might emanate from those files due to the changes I made to the `QuestTaskDocument` model in the `models.rs` file.

2024-09-28 09:36 UTC, Marchand-Nicolas requested changes
Missing `pub mod custom_api` in `src\endpoints\admin\mod.rs`.

2024-09-28 09:36 UTC, Marchand-Nicolas commented on src/endpoints/admin/custom_api/create_custom_api.rs
> +        .collect();
This part is unused

2024-09-28 20:33 UTC, Marchand-Nicolas requested changes
Very little change!

2024-09-28 20:33 UTC, Marchand-Nicolas commented on src/endpoints/mod.rs
> +pub mod custom_api;
This is not the right mod. There i a mod.rs in each folder. This is to indicate rust all the dependency tree. Every time, when adding a folder or a file, we need to update the mod.rs that is in the same directory. In your case, you added your folder in `src\endpoints\admin`, so you have to update `src\endpoints\admin\mod.rs`

2024-09-28 20:33 UTC, Marchand-Nicolas commented on src/endpoints/admin/custom_api/mod.rs
> +pub mod update_custom_api;
Here this mod.rs is setup perfectly

2024-09-28 20:35 UTC, Marchand-Nicolas commented
Also, I suggest you to try installing cargo so that you can try compiling or running the project, because all these issues are compiling issues, not even runtime issues

2024-09-28 21:33 UTC, GideonBature commented
Noted, sorry, an oversight from my own end, Thank you ser.

2024-09-29 07:53 UTC, Marchand-Nicolas approved these changes
Working really well! Lgtm

2024-09-29 07:53 UTC, merged