Feat/implement parse string
starknet-id/quest_server pull request #275
Opened 2024-09-29 04:40 UTC by JoelVR17

# Pull Request: Improve Function with Regex

## Description
This PR implements the `parse_string` function in the `verify_contract` and `verify_custom_api` routes to enhance the modularity of the task system, allowing for the use of dynamic strings when configuring tasks.

### Changes Made
- **Affected Files:**
  - `src/endpoints/quests/verify_contract.rs`
    - Implemented `parse_string` in `handler` to process the `call_data`.
    - Added regex validation to verify the contract call result.
  - `src/endpoints/quests/verify_custom_api.rs`
    - Applied `parse_string` to the `api_url` and improved API response handling.
  - `src/utils.rs`
    - Enhanced the `parse_string` function to utilize regex for pattern replacement in strings.

### Technical Details
- The `regex` library was used to handle patterns in strings, thereby improving validation and processing of dynamic inputs.
- Logic was added to convert addresses to hexadecimal and decimal using the `to_hex` function.

2024-09-29 09:14 UTC, Marchand-Nicolas requested changes
What you implemented is working really well, but you only implemented the parse_string function to call_data and and api_url, and forgot to do so with the regexs in both routes.  This would allow to have dynamic regex

2024-09-29 09:14 UTC, Marchand-Nicolas commented on src/endpoints/quests/verify_custom_api.rs
>          Ok(res) => {
Missing implementation of parse_string for the regex (you only did for the api_url)

2024-09-29 09:14 UTC, Marchand-Nicolas commented on src/endpoints/quests/verify_contract.rs
>                      if !regex.is_match(&result_str) {
Same here, parse_string should be implemented to the regex

2024-09-29 14:34 UTC, JoelVR17 commented on src/endpoints/quests/verify_contract.rs
>                      if !regex.is_match(&result_str) {
I got it, I'll work on it

2024-09-30 04:05 UTC, JoelVR17 commented
@Marchand-Nicolas the changes has been realized. If you need another thing, please let me know

2024-09-30 19:38 UTC, Marchand-Nicolas approved these changes
Working really well! GG, lgtm

2024-09-30 19:38 UTC, merged