Ft next id generate
starknet-id/quest_server pull request #277
Opened 2024-09-30 06:07 UTC by mubarak23

Draft PR for issue #274

2024-10-01 06:37 UTC, mubarak23 commented
getting specific state value not fix this error 
 @Marchand-Nicolas 
 
```
error[E0277]: the trait bound `fn(axum::extract::State<Arc<AppState>>, Extension<std::string::String>, axum::Json<create_balance::CreateBalance>) -> impl futures::Future<Output = impl IntoResponse> {create_balance::handler}: Handler<_, _, _>` is not satisfied
   --> src/endpoints/admin/balance/create_balance.rs:30:14
    |
29  | #[route(post, "/admin/tasks/balance/create", auth_middleware)]
    | -------------------------------------------------------------- required by a bound introduced by this call
30  | pub async fn handler(
    |              ^^^^^^^ the trait `Handler<_, _, _>` is not implemented for fn item `fn(State<Arc<AppState>>, Extension<String>, Json<CreateBalance>) -> impl Future<Output = impl IntoResponse> {handler}`
    |
    = help: the following other types implement trait `Handler<T, S, B>`:
              <Layered<L, H, T, S, B, B2> as Handler<T, S, B2>>
              <MethodRouter<S, B> as Handler<(), S, B>>
note: required by a bound in `post`
   --> /Users/macbookpro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-0.6.20/src/routing/method_routing.rs:407:1
    |
407 | top_level_handler_fn!(post, POST);
    | ^^^^^^^^^^^^^^^^^^^^^^----^^^^^^^
    | |                     |
    | |                     required by a bound in this function
    | required by this bound in `post`
    = note: this error originates in the macro `top_level_handler_fn` (in Nightly builds, run with -Z macro-backtrace for more info)
```

2024-10-01 09:19 UTC, Marchand-Nicolas commented
@mubarak23 Maybe check how we do in the other handlers to manage async functions calls

2024-10-03 11:34 UTC, Marchand-Nicolas commented
Hello @mubarak23 OD hack ends on Sunday (6). Everything okay ?

2024-10-03 23:57 UTC, Marchand-Nicolas commented
Hello, just got enough time to look at your problem @mubarak23 .

You are using Mutex from the std lib, which is not really usable inside of async functions. The best solution is to use Mutex from the Tokio Sync library: `use tokio::sync::Mutex;`

You can then simply do:
```rs
    let state_last_id = state.last_task_id.lock().await;
```

2024-10-04 12:23 UTC, Marchand-Nicolas requested changes
A lot of new imports that are not useful, and variables that are now unused

2024-10-04 12:23 UTC, Marchand-Nicolas commented on src/utils.rs
> +    // last_task_id = next_id.try_into().unwrap();
Remove this comment

2024-10-04 12:23 UTC, Marchand-Nicolas commented on src/utils.rs
> +        // next_id = *state_last_id;
Remove this comment

2024-10-04 12:23 UTC, Marchand-Nicolas commented on src/utils.rs
> +    // last_doc: Option<QuestTaskDocument>,
Remove this comment

2024-10-04 12:23 UTC, Marchand-Nicolas commented on src/utils.rs
> +    // let mut state_last_id =state.last_task_id.lock().unwrap();
Remove this comment

2024-10-04 12:23 UTC, Marchand-Nicolas commented on src/models.rs
> +use std::net::SocketAddr;
No need to import this module

2024-10-04 12:23 UTC, Marchand-Nicolas commented on src/utils.rs
> +use tokio::sync::Mutex;
No need to import that

2024-10-04 12:23 UTC, Marchand-Nicolas commented on src/endpoints/admin/balance/create_balance.rs
> +    // }
No need to keep these comments

2024-10-04 12:23 UTC, Marchand-Nicolas commented on src/endpoints/admin/balance/create_balance.rs
>      let last_doc = &collection.find_one(last_id_filter, options).await.unwrap();
You can remove this variable

2024-10-04 12:23 UTC, Marchand-Nicolas commented on src/endpoints/admin/balance/create_balance.rs
>      let last_doc = &collection.find_one(last_id_filter, options).await.unwrap();
Do the same in each route you modifed

2024-10-04 12:23 UTC, Marchand-Nicolas commented on src/endpoints/admin/quiz/create_question.rs
> +    QuestDocument, QuestInsertDocument, QuestTaskDocument, QuizInsertDocument, QuizQuestionDocument,
No need to import `QuestInsertDocument`

2024-10-04 12:47 UTC, Marchand-Nicolas commented on src/endpoints/admin/twitter/create_twitter_fw.rs
>      let options = FindOneOptions::builder().sort(doc! {"id": -1}).build();
options & last_id_filter unused

2024-10-04 12:50 UTC, Marchand-Nicolas requested changes

2024-10-04 12:50 UTC, Marchand-Nicolas commented on src/endpoints/admin/quiz/create_question.rs
> +    QuestDocument, QuestInsertDocument, QuestTaskDocument, QuizInsertDocument, QuizQuestionDocument,
Still there

2024-10-04 12:50 UTC, Marchand-Nicolas commented on src/endpoints/admin/quest_boost/create_boost.rs
>      let last_id_filter = doc! {};
Same options & last_id_filter unused, remove them from all the modified routes

2024-10-04 12:50 UTC, Marchand-Nicolas commented on src/utils.rs
> +    let mut next_id: i32 = 1;
Here I have the following warning:

```rs
value assigned to `next_id` is never read
maybe it is overwritten before being read?
`#[warn(unused_assignments)]` on by default
```

I think you can just not define this variable, and replace `next_id = ` by `return`

2024-10-04 14:38 UTC, Marchand-Nicolas commented on src/endpoints/admin/twitter/create_twitter_rw.rs
> +use crate::middleware::auth::auth_middleware;
You can remove `use mongodb::options::FindOneOptions;` from the imports

2024-10-04 14:38 UTC, Marchand-Nicolas commented on src/endpoints/admin/twitter/create_twitter_fw.rs
>      let last_id_filter = doc! {};
Unused variables

2024-10-04 14:40 UTC, Marchand-Nicolas requested changes

2024-10-04 14:40 UTC, Marchand-Nicolas commented on src/endpoints/admin/discord/create_discord.rs
> -use crate::models::{QuestDocument,QuestTaskDocument};
Your PR introduces a lot of warnings, please check the compilation before pushing: 
![image](https://github.com/user-attachments/assets/a39b7f4a-9f7e-4284-9745-39647c5006e9)

2024-10-04 15:35 UTC, Marchand-Nicolas approved these changes
Lgtm!

2024-10-04 15:37 UTC, merged