feat: Add GET Route /defi/rewards to Centralize DeFi Spring Reward Collection
starknet-id/quest_server pull request #280
Opened 2024-10-10 09:27 UTC by JoE11-y

### First Draft PR for #279 

### Work Done So Far 

1. Route and Input Validation: Implemented /defi/rewards route to centralize reward collection, with addr parameter validation.
2. HTTP Client with Middleware: Configured retry policy and tracing middleware for resilient, traceable HTTP requests.
3. Protocol Data Fetching: Created fetch rewards functions for ZkLend, Nostra, Nimbora, and Ekubo, handling errors by defaulting to empty vectors.
4. Centralized Reward Struct: Defined CommonReward struct and RewardSource enum to standardize protocol data.
5. Call Generation: Implemented create_calls to map reward data to Call objects for streamlined claiming.
6. JSON Response Construction: Built a unified response with rewards and calls, grouped by protocol for easy consumption.

### Work Remaining (One-liners)
1. Error Handling Refinements and  error logging.
2. Test Coverage:  integration tests for each fetch function and integration tests for the /defi/rewards route.

### Call Data

The data structures for each protocol claims are outlined below, along with links to sample transactions that informed the structure.

#### 1. Nimbora
- **Sample Transaction**: [Nimbora Claim on StarkScan](https://starkscan.co/call/0x06da50f3a0fb3f96032afed3ab50e567f2bbb250d17029d104c54723917055a8_1_1)
- **Data Structure**:
  ```rust
  {
      amount: String,
      proof: Vec<String>
  }
  ```

#### 2. ZkLend
- **Sample Transaction**: [ZkLend Claim on StarkScan](https://starkscan.co/call/0x04399e0892d054c744eb768123b72fba98200779574a403926d8133c7040907c_1_7)
- **Data Structure**:
  ```rust
  {
      claim: {
          id: u64,
          amount: String,
          claimee: String,
      },
      proof: Vec<String>
  }
  ```

#### 3. Nostra
- **Sample Transaction**: [Nostra Claim on StarkScan](https://starkscan.co/call/0x02ae9e6a0abd0be6fac315a20d16a35240f58d70f777f5532cdc02e6734b5379_1_25)
- **Data Structure**:
  ```rust
  {
      amount: String,
      proof: Vec<String>
  }
  ```

#### 4. Ekubo
- **Sample Transaction**: [Ekubo Claim on StarkScan](https://starkscan.co/call/0x03e6562b720cd7fddc8503550c98569cd85f44ee19dfefe0a0fa7b5bc8b5b235_1_1)
- **Data Structure**:
  ```rust
  {
      claim: {
          id: u64,
          amount: String,
          claimee: String,
      },
      proof: Vec<String>
  }
  ```
  
  
  Any insights or optimizations would be appreciated.

2024-10-11 14:33 UTC, Marchand-Nicolas requested changes
Some changes are required to be able to run the multicall.

Also, don't forget to try putting the returned call_data in a multicall to test if it works

2024-10-11 14:33 UTC, Marchand-Nicolas commented on .env
> +HOST="http://0.0.0.0:8080"
Remove this part

2024-10-11 14:33 UTC, Marchand-Nicolas commented on src/endpoints/defi/rewards.rs
> +    "0x008faa2edc6833a6ad0625f1128d56cf471c3f9649ff2201d9ef49d7e9bb18de";
Set these constants in config.toml & config.template.toml

2024-10-11 14:33 UTC, Marchand-Nicolas commented on src/endpoints/defi/rewards.rs
> +    let addr = match params.get("addr") {
We often use dec and not hex number, you can check in `src/endpoints/has_completed_quest.rs` how we manage to handle both easily

2024-10-11 14:33 UTC, Marchand-Nicolas commented on src/endpoints/defi/rewards.rs
> +                .map(|doc| CommonReward {
No need to return all these fields for the rewards array. Only keep the amount and the token name.
The aim is to have the necessary data to build this modal:
<img width="787" alt="image" src="https://github.com/user-attachments/assets/85148dd0-6ac2-42a0-a92e-4e54127d5ccc">
(Except Vesu that we'll add later)

2024-10-11 14:33 UTC, Marchand-Nicolas commented on src/endpoints/defi/rewards.rs
> +fn create_calls(rewards: &[CommonReward], addr: &str) -> Vec<Call> {
When testing the endpoint, the calls field is not an array:
<img width="320" alt="image" src="https://github.com/user-attachments/assets/fe26701b-7de1-46f8-884b-2ffd774ec17d">.
This should simply be an array as following:
```json
"calls": [
   {
        "contract": "0x1a9acedc9a858ec3a2b6e5b2540aab67c6fab3376c5d56b44dfc3c18d727663",
        "call_data": [...],
        "entry_point": "claim",
   },
...
]
````
Also, why did you added a "regex" field ?

In addition, the calldata is not well formatted.
<img width="546" alt="image" src="https://github.com/user-attachments/assets/e97c5928-7596-430e-aeae-53973259f74a">
This should be an array of string. Every calldata should be formatted depending the protocol. To know what format each protocol expects, check on starkscan their contract. E.g. for Zklend:
<img width="885" alt="image" src="https://github.com/user-attachments/assets/a473761f-c8ed-4b83-847c-5c2bbb2ea023">

2024-10-11 17:36 UTC, JoE11-y commented on .env
> +HOST="http://0.0.0.0:8080"
alright noted.

2024-10-11 17:36 UTC, JoE11-y commented on src/endpoints/defi/rewards.rs
> +    "0x008faa2edc6833a6ad0625f1128d56cf471c3f9649ff2201d9ef49d7e9bb18de";
alright noted.

2024-10-11 17:37 UTC, JoE11-y commented on src/endpoints/defi/rewards.rs
> +    let addr = match params.get("addr") {
okay will take a look at it.

2024-10-11 17:37 UTC, JoE11-y commented on src/endpoints/defi/rewards.rs
> +                .map(|doc| CommonReward {
alright will remove redundant data.

2024-10-11 17:38 UTC, JoE11-y commented on src/endpoints/defi/rewards.rs
> +fn create_calls(rewards: &[CommonReward], addr: &str) -> Vec<Call> {
Okay will crosscheck the calls,

I actually reused the call struct in the models and the regex was a requirement there to be used in endpoints/quests/verify_contract

maybe i'll just create a new struct for it.

2024-10-11 21:52 UTC, Marchand-Nicolas commented on src/endpoints/defi/rewards.rs
> +fn create_calls(rewards: &[CommonReward], addr: &str) -> Vec<Call> {
Yes it's not for the same thing

2024-10-13 18:40 UTC, Marchand-Nicolas approved these changes
Lgtm!

2024-10-13 18:41 UTC, merged