Fix 320
starknet-id/quest_server pull request #331
Opened 2024-11-22 17:57 UTC by DioChuks

Close #320

2024-11-23 17:08 UTC, Marchand-Nicolas requested changes

2024-11-23 17:08 UTC, Marchand-Nicolas commented on src/endpoints/defi/rewards.rs
> +        // .with(TracingMiddleware::new())
Why ? You can keep `.with(TracingMiddleware::default())`

2024-11-23 17:08 UTC, Marchand-Nicolas commented on src/utils.rs
>  pub async fn make_api_request(endpoint: &str, addr: &str, api_key: Option<&str>) -> bool {
Please remove this function

2024-11-23 17:08 UTC, Marchand-Nicolas commented on src/utils.rs
> +    #[allow(dead_code)]
And remove this one

2024-11-23 17:08 UTC, Marchand-Nicolas commented on src/common/verify_has_root_or_braavos_domain.rs
>  pub async fn verify_has_root_or_braavos_domain(
Remove this code rather than allowing dead code

2024-11-23 21:31 UTC, DioChuks commented on src/endpoints/defi/rewards.rs
> +        // .with(TracingMiddleware::new())
There was an error that appeared in the code, when I looked at it, this was the message:

the trait bound `TracingMiddleware<DefaultSpanBackend>: reqwest_middleware::Middleware` is not satisfied
the trait `reqwest_middleware::Middleware` is implemented for `RetryTransientMiddleware<T, R>`
required for `TracingMiddleware<DefaultSpanBackend>` to implement `reqwest_middleware::Middleware`

"It could have been a version issue compatibility, that's why I commented it out, I tried some workaround but nothing worked, as commenting it out for now, didn't break anything even after testing. But as per your request, I'll uncomment it." I noticed the `default` that was changed to `new`, must have missed it when I commented it out.

2024-11-23 21:34 UTC, DioChuks commented on src/utils.rs
>  pub async fn make_api_request(endpoint: &str, addr: &str, api_key: Option<&str>) -> bool {
alright

2024-11-23 21:34 UTC, DioChuks commented on src/utils.rs
> +    #[allow(dead_code)]
okay, working on it!

2024-11-23 21:36 UTC, DioChuks commented on src/common/verify_has_root_or_braavos_domain.rs
>  pub async fn verify_has_root_or_braavos_domain(
The macro `#[allow(dead_code)]` does silence the warnings that come with running `cargo build` for unused variables, but as per your instructions, I'll remove it

2024-11-24 10:19 UTC, Marchand-Nicolas requested changes
<img width="787" alt="image" src="https://github.com/user-attachments/assets/ba212529-88e3-41b7-8672-25c9b86420e4">
Please delete these functions

2024-11-24 10:19 UTC, Marchand-Nicolas commented on src/main.rs
> +#[allow(dead_code)]
Don't allow dead code, remove it instead

2024-11-24 10:19 UTC, Marchand-Nicolas commented on src/main.rs
> +#[allow(dead_code)]
Don't allow dead code, remove it instead

2024-11-24 10:19 UTC, Marchand-Nicolas commented on src/models.rs
>  pub_struct!(Deserialize; CompletedTasks {
Please remove tehse "_", even though it will generate warnings, these ones are not important

2024-11-24 12:37 UTC, DioChuks commented on src/models.rs
>  pub_struct!(Deserialize; CompletedTasks {
Alright, i'll do that!

2024-11-24 12:56 UTC, DioChuks commented on src/main.rs
> +#[allow(dead_code)]
Alright

2024-11-24 13:04 UTC, DioChuks commented on src/main.rs
> +#[allow(dead_code)]
On it!

2024-11-25 11:54 UTC, Marchand-Nicolas requested changes

2024-11-25 11:54 UTC, Marchand-Nicolas commented on src/common/verify_has_root_or_braavos_domain.rs
> +//     sync::Arc,
Please don't comment unused code

Just delete the whole file

2024-11-25 11:54 UTC, Marchand-Nicolas commented on src/config.rs
> +    _address: String
Please remove all the _ you added at the start of variable names

2024-11-25 11:54 UTC, Marchand-Nicolas commented on src/models.rs
> +    _addr: FieldElement,
Same remvove the _

2024-11-25 11:54 UTC, Marchand-Nicolas commented on src/utils.rs
> +// use serde_json::json;
Don't comment unused code. Just remove the unused code

2024-11-25 12:42 UTC, DioChuks commented on src/common/verify_has_root_or_braavos_domain.rs
> +//     sync::Arc,
Alright, on it!

2024-11-25 12:43 UTC, DioChuks commented on src/config.rs
> +    _address: String
Oh!, understood. Making the changes now.

2024-11-25 12:44 UTC, DioChuks commented on src/models.rs
> +    _addr: FieldElement,
Okay.

2024-11-25 16:15 UTC, Marchand-Nicolas approved these changes
Well done lgtm!

2024-11-25 16:15 UTC, merged

2024-11-25 16:17 UTC, Marchand-Nicolas commented on src/endpoints/defi/rewards.rs
> +        // .with(TracingMiddleware::new())
I see thanks for the clarification