Fix: Implement get_quest_users admin route
starknet-id/quest_server pull request #334
Opened 2024-11-23 22:39 UTC by MrRoudyk

Changes Made:
Updated dependencies
Added get_quest_users Route
Added tests

Added lib.rs for proper organization of Imports in endpoints.rs
Before running the tests, you must manually add an admin user with the following credentials:
user: test_user
code: 10227906493930071616
These credentials are specified in the config.template.toml file as shown below:

[get_quest_users]
test_user = "test_user"
test_password = "test_password"
test_hashed_code = "10227906493930071616"

Closes #326

2024-11-23 22:45 UTC, MrRoudyk commented
@Marchand-Nicolas can you take a look at this draft? I had to add lib.rs for testing. Not sure if that's right

2024-11-24 10:26 UTC, Marchand-Nicolas requested changes
Use the auth system we have already setup in other admin routes

```rs
    let res = verify_quest_auth(sub, &quests_collection, &(body.quest_id as i64)).await;
    if !res {
        return get_error("Error creating task".to_string());
    };
```

2024-11-24 10:26 UTC, Marchand-Nicolas commented on config.template.toml
> +[get_quest_users]
No need to add that

2024-11-24 10:26 UTC, Marchand-Nicolas commented on Cargo.toml
> +reqwest-middleware = { version = "0.4", features = ["json"] }
Please don't update the libs

2024-11-24 10:26 UTC, Marchand-Nicolas commented on src/config.rs
> +    test_user: String,
Please don't modify the config

2024-11-24 10:26 UTC, Marchand-Nicolas commented on src/lib.rs
> +pub mod utils;
No need to have this file

2024-11-24 10:26 UTC, Marchand-Nicolas commented on src/main.rs
> -mod config;
Do no modify main.rs

2024-11-24 10:26 UTC, Marchand-Nicolas commented on src/models.rs
> -    pub(crate) id: i32,
Why ?

2024-11-24 10:26 UTC, Marchand-Nicolas commented on tests/endpoints.rs
> +            .get(&endpoint)
No need to have tests for this route

2024-11-24 11:13 UTC, MrRoudyk commented
@Marchand-Nicolas thanks for the feedback. I'll make the corrections today and submit the PR, changing the label to "ready for review".

2024-11-24 16:24 UTC, MrRoudyk commented on Cargo.toml
> +reqwest-middleware = { version = "0.4", features = ["json"] }
I had to do this because the project wouldn't build until I updated the dependencies.
```
error[E0277]: the trait bound `TracingMiddleware<DefaultSpanBackend>: reqwest_middleware::Middleware` is not satisfied
--> src/endpoints/defi/rewards.rs:40:15
```
Now I saw the solution in telegram

2024-11-24 16:31 UTC, MrRoudyk commented on tests/endpoints.rs
> +            .get(&endpoint)
I probably misunderstood the tasks.
> Testing:
> Functional Tests:
> Test with a valid quest_id that has tasks and participants.
> Test with a quest_id that has tasks but no participants.
> Test with an invalid quest_id to ensure appropriate error handling.
> Authentication Tests:
> Verify that unauthorized access is blocked by the auth_middleware.
> Edge Cases:
> Test with a quest that has no tasks to ensure the route handles this gracefully.
But if tests are not needed, then how to implement these tasks?

2024-11-25 12:04 UTC, Marchand-Nicolas approved these changes
Working perfectly lgtm!

2024-11-25 12:05 UTC, merged