Reinforce the WatchTower implementation
starknet-id/quest_server pull request #336
Opened 2024-11-24 12:59 UTC by Michaelkingsdev

Closes #321 

The following files were modified
1. utils.rs
2. rewards.rs
3. get_alt_protocol_stats.rs

Is there any need to modify `logger.rs`

2024-11-24 12:59 UTC, Michaelkingsdev commented
@Marchand-Nicolas 
Review

2024-11-25 12:08 UTC, Marchand-Nicolas requested changes
Looks very good! Please pull the changes made on the testnet branch, because they contain a fix for the build error you might have experienced. It will allow me to test it

2024-11-25 12:08 UTC, Marchand-Nicolas commented on src/utils.rs
> +            logger.info(format!(
Please use logger.severe, because it's an error

2024-11-25 15:55 UTC, Michaelkingsdev commented on src/utils.rs
> +            logger.info(format!(
Alright

2024-11-25 16:06 UTC, Michaelkingsdev commented
> Looks very good! Please pull the changes made on the testnet branch, because they contain a fix for the build error you might have experienced. It will allow me to test it

Done @Marchand-Nicolas

2024-11-26 18:38 UTC, Marchand-Nicolas approved these changes
Lgtm!

2024-11-26 18:38 UTC, merged