added tests totest_to_hex and test_to_hex_trimmed
starknet-id/quest_server pull request #338
Opened 2024-11-24 20:36 UTC by guha-rahul

close #322

2024-11-24 20:38 UTC, guha-rahul commented on tests/utils.rs
> +    use crate::utils::{to_hex, to_hex_trimmed};
had some trouble importing the functions. would require some help on this

2024-11-25 12:16 UTC, Marchand-Nicolas commented
@guha-rahul  In fact, (I didn't sorry), the convention is to put the tests in the same file where the function you are testing is wrote https://doc.rust-lang.org/book/ch11-03-test-organization.html#:~:text=You'll%20put%20unit%20tests,module%20with%20cfg(test)%20.

So you can directly put them there

2024-11-25 12:59 UTC, Marchand-Nicolas commented
Ah @guha-rahul this dev found a good solution, you can check it: https://github.com/lfglabs-dev/api.starknet.id/pull/112
I think it's better than having the tests in the same file (because utils.rs is already huge)

2024-11-27 13:57 UTC, Marchand-Nicolas commented
Please resolve the conflicts so that I can merge

2024-11-27 14:02 UTC, Marchand-Nicolas requested changes

2024-11-27 14:02 UTC, Marchand-Nicolas commented on src/tests/mod.rs
> +mod utils;
Also add mod endpoints

2024-11-28 11:31 UTC, Marchand-Nicolas requested changes

2024-11-28 11:31 UTC, Marchand-Nicolas commented on src/main.rs
> +}
This is not needed, and it doesn't build.
I think you can just keep

```rs
#[cfg(test)]
mod tests;
```

2024-11-29 10:14 UTC, Marchand-Nicolas approved these changes
Well done lgtm!

2024-11-29 10:14 UTC, merged