Fix#351Update mongo setup in the README
starknet-id/quest_server pull request #355
Opened 2024-12-16 06:59 UTC by Amarjeet325

close: #351

2024-12-16 11:02 UTC, Marchand-Nicolas requested changes

2024-12-16 11:02 UTC, Marchand-Nicolas commented on README.md
> +### Install Docker(optional)
Space missing before the "("

2024-12-16 11:02 UTC, Marchand-Nicolas commented on README.md
> +- `connection_string`, this is the string to connect to the database.Replace with the MongoDB Atlas connection string here.
Space missing before "Replace"

2024-12-17 06:12 UTC, Amarjeet325 commented
Hi @Marchand-Nicolas  , Can You recheck my PR , I have  make changes  according to request .

2024-12-17 10:56 UTC, Marchand-Nicolas approved these changes
Perfect lgtm!

2024-12-17 10:56 UTC, merged