Fix: Move get_quest_users.rs to the correct directory
starknet-id/quest_server pull request #356
Opened 2024-12-16 08:38 UTC by Nanle100

### What does this PR do?  
This PR reorganizes the file structure by moving the `get_quest_users.rs` file from `src/endpoints/admin/quest_boost/` to `src/endpoints/admin/quest/`.  

### Why is this needed?  
The updated path reflects a more logical organization of the codebase, aligning `get_quest_users.rs` with its relevant module (`quest`) instead of the unrelated `quest_boost`.

### Changes Made:  
1. Moved `src/endpoints/admin/quest_boost/get_quest_users.rs` to `src/endpoints/admin/quest/get_quest_users.rs`.  
2. Updated all references in the codebase to reflect the new file location.  
3. Checked and updated relevant `mod.rs` files to ensure proper module imports.

### Testing Notes:  
- Verified that all references to `get_quest_users.rs` are updated correctly.  
- Checked that module imports in `mod.rs` files (if applicable) include the file without errors.  
- Confirmed functionality remains unaffected post-refactor.

2024-12-16 10:59 UTC, Marchand-Nicolas requested changes

2024-12-16 10:59 UTC, Marchand-Nicolas commented on Cargo.toml
> +
These empty lines are not needed

2024-12-16 11:49 UTC, Nanle100 commented on Cargo.toml
> +
okay

2024-12-17 10:51 UTC, Marchand-Nicolas approved these changes
Lgtm!

2024-12-17 10:54 UTC, merged