Fix: Include quest completion timestamp in get_quest_participants res…
starknet-id/quest_server pull request #359
Opened 2024-12-25 11:31 UTC by TropicalDog17

…ponse

2025-01-02 11:48 UTC, Marchand-Nicolas commented
Hello @TropicalDog17 when will the PR be ready for review ?

2025-01-03 03:01 UTC, TropicalDog17 commented
Hey please review this PR. Thank you so much! @Marchand-Nicolas

2025-01-07 14:14 UTC, Marchand-Nicolas commented on src/config.rs
> +    } else if (args.len() > 1) && (args.get(1).unwrap().contains("toml")) {
Why ?

2025-01-07 14:20 UTC, Marchand-Nicolas requested changes
As said in the issue, the route we want to update is src/endpoints/admin/quest/get_quest_participants.rs, not src/endpoints/get_quest_participants.rs,

2025-01-07 14:20 UTC, Marchand-Nicolas commented on src/tests/endpoints.rs
> +    // pub async fn test_get_quest_participants() {
You can remove this

2025-01-07 14:20 UTC, Marchand-Nicolas commented on src/endpoints/get_quest_participants.rs
> +#[cfg(test)]
No need to have the tests, but it was a good idea to make sure everything was working. The problem is that if we run tests in production, it'll reset the db

2025-01-20 10:19 UTC, Marchand-Nicolas commented
Hello @TropicalDog17 everything good ?

2025-01-20 17:06 UTC, TropicalDog17 commented
Hi sorry for the delay, can you review @Marchand-Nicolas

2025-01-22 15:09 UTC, Marchand-Nicolas requested changes

2025-01-22 15:09 UTC, Marchand-Nicolas commented on src/config.rs
> +    } else {
No need to have these changes, you can revert

2025-01-22 15:09 UTC, Marchand-Nicolas commented on src/tests/endpoints.rs
> +    // #[tokio::test]
No need to have these comments

2025-01-22 15:09 UTC, Marchand-Nicolas commented on src/endpoints/admin/quest/get_quest_participants.rs
> +// #[cfg(test)]
No need to have these comments

2025-01-22 15:09 UTC, Marchand-Nicolas commented on src/endpoints/admin/quest/get_quest_participants.rs
> +            "max_timestamp": { "$max": "$timestamp.$numberLong" }
Error aggregating completed tasks: Kind: Command failed: Error code 16410 (Location16410): FieldPath field names may not start with '$'. Consider using $getField or $setField., labels: {}

2025-01-24 17:37 UTC, Marchand-Nicolas commented
Hello @TropicalDog17 everything good ?

2025-01-25 10:01 UTC, TropicalDog17 commented
Hi @Marchand-Nicolas I struggle to debug this, since I am not quite able to setup the enviroment properly, can you help me? Sorry for any inconvenience

2025-01-25 14:23 UTC, Marchand-Nicolas commented
Hello @TropicalDog17 here is a guide to help you setup the project: https://github.com/lfglabs-dev/api.starknet.quest/blob/testnet/README.md
You need to update this file: src/endpoints/admin/quest/get_quest_participants.rs
An example pipeline has been provided in the issue. You might just need to copy paste it

2025-01-29 09:19 UTC, Marchand-Nicolas commented
Hello @TropicalDog17 Can I assign someone else ? It's been more than a month

2025-01-29 12:06 UTC, TropicalDog17 commented
> Hello @TropicalDog17 here is a guide to help you setup the project: https://github.com/lfglabs-dev/api.starknet.quest/blob/testnet/README.md You need to update this file: src/endpoints/admin/quest/get_quest_participants.rs An example pipeline has been provided in the issue. You might just need to copy paste it

The pipeline not work i think

2025-01-29 12:17 UTC, TropicalDog17 commented
@Marchand-Nicolas could you help me test the pipeline, I am able to set up the project and authen the admin route, create new quest. But I am not able to populate some tasks for testing. I think it will be a good idea to has some scripts for populate some mock data for testing.
 And it seems the project has very low code coverage, I tried to write some tests but it is very difficult the way the project is written.

2025-01-29 12:34 UTC, Marchand-Nicolas commented
> @Marchand-Nicolas could you help me test the pipeline, I am able to set up the project and authen the admin route, create new quest. But I am not able to populate some tasks for testing. I think it will be a good idea to has some scripts for populate some mock data for testing. And it seems the project has low test coverage, I tried to write some tests but it is very difficult the way the project is written.

You can run the frontend to add tasks https://github.com/lfglabs-dev/starknet.quest/

2025-01-29 12:35 UTC, Marchand-Nicolas commented
You can test your pipeline in Compass

2025-01-29 17:34 UTC, Marchand-Nicolas approved these changes
lgtm

2025-01-29 17:34 UTC, merged